[package]
name = "brwallet"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
ripemd = "0.1"
secp256k1 = { version = "0.29", features = ["global-context", "rand-std"] }
bs58 = { version = "0.5", features = ["check"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10"
memmap2 = "0.9"
hex = "0.4"